name: Pytest Playwright

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright Browsers
        run: |
          playwright install --with-deps
      - name: Run tests
        env:
          APP_URL: ${{ secrets.APP_URL }}
          API_BASE: ${{ secrets.API_BASE }}
          TEST_API_TOKEN: ${{ secrets.TEST_API_TOKEN }}
          TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          TEST_COMP2_EMAIL: ${{ secrets.TEST_COMP2_EMAIL }}
          TEST_COMP2_PASSWORD: ${{ secrets.TEST_COMP2_PASSWORD }}
        run: pytest -q
